Nucleus N13()
{
    Nucleus ThisNuc;
    ThisNuc.SetName("N13");
    ThisNuc.SetZ(7);
    ThisNuc.SetA(13);
    ThisNuc.SetLifeTime("sec",9.965*60.0);
    ThisNuc.SetAbundance("Dimless",0.0);
    ThisNuc.SetBindingEnergy("PerN","MeV",7.23886321);
    
    // Add list of levels:
    Int_t Key = 0;
    Key=0; ThisNuc.AddEnergyLevel(Key,0.0,"keV"); 
    ++Key; ThisNuc.AddEnergyLevel(Key,2364.9,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,3502.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,3547.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,6364.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,6886.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,7155.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,7376.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,7900.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,8918.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,9000.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,9476.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,10250.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,10360.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,10360.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,10833.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,11530.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,11700.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,11740.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,11740.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,11860.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,12130.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,12558.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,12937.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,13500.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,14050.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,15064.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,15300.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,15990.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,16000.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,17500.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,18150.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,18170.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,18406.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,18961.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,19830.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,19880.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,20200.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,20900.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,21400.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,21700.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,22400.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,23000.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,23300.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,23830.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,23900.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,24400.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,24600.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,25600.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,25900.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,26840.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,28000.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,31000.0,"keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,32000.0,"keV");

    // Add parities:
    Key=0; ThisNuc.AddLevelAngMom(Key,0.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,3.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,4.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"+",kFALSE);
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,3.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,3.5,"-",kTRUE); 
    ++Key;
    ++Key;
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kFALSE);
    ++Key; ThisNuc.AddLevelAngMom(Key,3.5,"+",kTRUE); 
    ++Key;
    ++Key;
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kTRUE); ThisNuc.AddLevelAngMom(Key,3.5,"-",kTRUE);
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,3.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,2.5,"-",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"+",kTRUE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,0.5,"+",kTRUE); 
    ++Key;
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kFALSE); 
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kFALSE);
    ++Key; ThisNuc.AddLevelAngMom(Key,5.5,"-",kFALSE);
    ++Key;
    ++Key;
    ++Key; ThisNuc.AddLevelAngMom(Key,1.5,"-",kFALSE); 
    
    // return the answer:
    return ThisNuc;
}
