Nucleus Sb122()
{
    // Basic properties:
    Nucleus ThisNuc;
    ThisNuc.SetName("Sb122");
    ThisNuc.SetZ(51);
    ThisNuc.SetA(122);
    ThisNuc.SetLifeTime("sec",2.7238*24.0*3600.0);
    ThisNuc.SetAbundance("Dimless",0.0);
    ThisNuc.SetBindingEnergy("PerN","MeV",8.46831723);
    ThisNuc.SetSp("MeV",6.425);
    ThisNuc.SetSn("MeV",6.806);
    
    // Adding the level scheme:
    Int_t Key = 0;
    Key=0; ThisNuc.AddEnergyLevel(Key,0.0,"keV"); ThisNuc.SetLevelReference(Key,"ABCDFGHI"); ThisNuc.AddLevelAngMom(Key,2,"-",kTRUE); ThisNuc.SetLevelLifeTime(Key,2.7238,"day");
    ++Key; ThisNuc.AddEnergyLevel(Key,61.41315,"keV"); ThisNuc.SetLevelReference(Key,"ABCDEFGH"); ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE); ThisNuc.SetLevelLifeTime(Key,1.86,"us"); ThisNuc.AddLevelGamma(Key,61.4127,100.0,0.0,"E1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,78.09146,"keV"); ThisNuc.SetLevelReference(Key,"ABCD"); ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,78.09187,100.0,0.0,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,121.4967,"keV"); ThisNuc.SetLevelReference(Key,"ABDEG"); ThisNuc.AddLevelAngMom(Key,1,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,6.3,"ns"); ThisNuc.AddLevelGamma(Key,121.495814,100.0,0.0,"E1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,137.47268,"keV"); ThisNuc.SetLevelReference(Key,"ADFGH"); ThisNuc.AddLevelAngMom(Key,5,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.53,"ms"); ThisNuc.AddLevelGamma(Key,76.0595,100.0,61.4131,"E2","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,163.559117,"keV"); ThisNuc.SetLevelReference(Key,"AEFHI"); ThisNuc.AddLevelAngMom(Key,8,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,4.191,"s"); ThisNuc.AddLevelGamma(Key,26.086724,100.0,137.4726,"E3","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,167.22936,"keV"); ThisNuc.SetLevelReference(Key,"ABDF"); ThisNuc.AddLevelAngMom(Key,2,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.28,"ns"); ThisNuc.AddLevelGamma(Key,45.73259,13.216,121.4967,"M1","keV");
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,89.138818,2.1313,78.0914,"E1","keV");
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,105.81607,100.0,61.4131,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,178.64,"keV"); ThisNuc.SetLevelReference(Key,"B");
    ++Key; ThisNuc.AddEnergyLevel(Key,192.959410,"keV"); ThisNuc.SetLevelReference(Key,"ABCDFG"); ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.11,"ns"); ThisNuc.AddLevelGamma(Key,114.86749,100.0,78.0914,"M1+E2","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,209.65086,"keV"); ThisNuc.SetLevelReference(Key,"ABCDFG"); ThisNuc.AddLevelAngMom(Key,4,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,72.1788,0.89,137.4726,"M1","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,148.23764,100.0,61.4131,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,255.49868,"keV"); ThisNuc.SetLevelReference(Key,"ABDE"); ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.9,"ns"); ThisNuc.AddLevelGamma(Key,45.8474,9.213,209.6508,"M1","keV");
                                                                                                                                                                                 ThisNuc.AddLevelGamma(Key,88.268910,100.0,167.2293,"M1","keV");
                                                                                                                                                                                 ThisNuc.AddLevelGamma(Key,177.407320,10.22,78.0914,"E1","keV");
                                                                                                                                                                                 ThisNuc.AddLevelGamma(Key,194.082016,64.113,61.4131,"M1","keV");
                                                                                                                                                                                 ThisNuc.AddLevelGamma(Key,255.503922,36.67,0.0,"E1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,264.426013,"keV"); ThisNuc.SetLevelReference(Key,"ADF"); ThisNuc.AddLevelAngMom(Key,5,"-",kFALSE); ThisNuc.AddLevelGamma(Key,71.466410,100.0,192.9594,"M1","keV");
                                                                                                                                         ThisNuc.AddLevelGamma(Key,186.3368,1.6,78.0914,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,265.111116,"keV"); ThisNuc.SetLevelReference(Key,"AF"); ThisNuc.AddLevelAngMom(Key,7,"-",kFALSE); ThisNuc.AddLevelGamma(Key,101.55168,100.0,163.5591,"M1+E2","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,271.763015,"keV"); ThisNuc.SetLevelReference(Key,"AG"); ThisNuc.AddLevelGamma(Key,7.336622,100.0,264.4260,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,282.64998,"keV"); ThisNuc.SetLevelReference(Key,"ABCDE"); ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,89.6914,1.00,192.9594,"M1","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,115.42037,4.2,167.2293,"E1","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,204.559111,13.5,78.0914,"M1","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,221.2445,1.17,61.4131,"??","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,282.6423,100.0,0.0,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,311.261214,"keV"); ThisNuc.SetLevelReference(Key,"ABCD"); ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,28.6074,0.0,282.6499,"??","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,46.8366,8.8,264.4260,"M1","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,118.301416,6.05,192.9594,"??","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,173.834,2.5,137.4726,"??","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,233.1744,100.0,78.0914,"M1","keV");    
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,249.8576,4.47,61.4131,"??","keV");
                                                                                                                                                                                   ThisNuc.AddLevelGamma(Key,311.291,6.47,0.0,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,323.092212,"keV"); ThisNuc.SetLevelReference(Key,"ABDEG"); ThisNuc.AddLevelAngMom(Key,2,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,67.595216,9.0,255.4986,"M1","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,155.8675,1.79,167.2293,"??","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,201.594315,100.0,121.4967,"M1","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,261.6744,9.6,61.4131,"??","keV");                                                                                                                                                                        
    ++Key; ThisNuc.AddEnergyLevel(Key,333.68018,"keV"); ThisNuc.SetLevelReference(Key,"ABDEF"); ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.0,"ps"); ThisNuc.AddLevelGamma(Key,124.029310,49.3,209.6508,"M1","keV");
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,140.72715,1.62,192.9594,"??","keV");
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,166.451111,100.0,167.2293,"M1","keV");
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,272.2653,25.2,61.4131,"M1+E2","keV");                                                                                                                                                                              
    ++Key; ThisNuc.AddEnergyLevel(Key,393.699311,"keV"); ThisNuc.SetLevelReference(Key,"ADEFG"); ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,138.2013,11.7,255.4986,"M1+E2","keV");
                                                                                                 ThisNuc.AddLevelAngMom(Key,4,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,184.047414,47.8,209.6508,"M1","keV");
                                                                                                 ThisNuc.AddLevelAngMom(Key,5,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,256.230,17.8,137.4726,"??","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,332.284,100.0,61.4131,"M1+E2","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,396.937310,"keV"); ThisNuc.SetLevelReference(Key,"ADCDE"); ThisNuc.AddLevelAngMom(Key,2,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.11,"ns"); ThisNuc.AddLevelGamma(Key,73.84012,6.4,323.0922,"??","keV");
                                                                                                 ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,141.436813,100.0,255.4986,"M1","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,229.7073,35.4,167.2293,"??","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,275.4444,15.0,121.4967,"??","keV");
                                                                                                                                                                                    ThisNuc.AddLevelGamma(Key,335.49719,10.9,61.4131,"??","keV");                                                                                                                                                                                                                                                                                                                                            
    ++Key; ThisNuc.AddEnergyLevel(Key,410.120,"keV"); ThisNuc.SetLevelReference(Key,"C");                                                                                                                                                                     
    ++Key; ThisNuc.AddEnergyLevel(Key,413.765716,"keV"); ThisNuc.SetLevelReference(Key,"AEF"); ThisNuc.AddLevelAngMom(Key,6,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.0,"ps"); ThisNuc.AddLevelGamma(Key,148.65436,100.0,265.1111,"M1","keV");
                                                                                                                                                                                ThisNuc.AddLevelGamma(Key,149.339213,45.7,264.4260,"M1","keV");                                                                                                                                                                                     
    ++Key; ThisNuc.AddEnergyLevel(Key,416.2,"keV"); ThisNuc.SetLevelReference(Key,"F"); ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE);
                                                                                        ThisNuc.AddLevelAngMom(Key,4,"+",kTRUE);  
    ++Key; ThisNuc.AddEnergyLevel(Key,425.148414,"keV"); ThisNuc.SetLevelReference(Key,"ADEF"); ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,113.88675,35.5,311.2612,"M1(+E2)","keV");
                                                                                                ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE);                                          ThisNuc.AddLevelGamma(Key,153.38538,22.1,271.7630,"??","keV");
                                                                                                ThisNuc.AddLevelAngMom(Key,5,"-",kFALSE);                                          ThisNuc.AddLevelGamma(Key,232.1893,100.0,192.9594,"M1","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,453.747820,"keV"); ThisNuc.SetLevelReference(Key,"AF"); ThisNuc.AddLevelAngMom(Key,1,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.21,"ns"); ThisNuc.AddLevelGamma(Key,286.517721,100.0,167.2293,"M1+E2","keV");
                                                                                              ThisNuc.AddLevelAngMom(Key,2,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,392.34011,31.7,61.4131,"??","keV");
                                                                                              ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,453.774,33.0,0.0,"??","keV");                                                                                                                                                                        
    ++Key; ThisNuc.AddEnergyLevel(Key,474.2,"keV"); ThisNuc.SetLevelReference(Key,"CFG"); ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE);
                                                                                          ThisNuc.AddLevelAngMom(Key,4,"+",kTRUE);  
    ++Key; ThisNuc.AddEnergyLevel(Key,480.43611,"keV"); ThisNuc.SetLevelReference(Key,"AE"); ThisNuc.AddLevelGamma(Key,208.67312,100.0,271.76230,"??","keV");
                                                                                             ThisNuc.AddLevelGamma(Key,215.285,44.0,265.1111,"??","keV");                                                                                                                                                                          
    ++Key; ThisNuc.AddEnergyLevel(Key,481.3395,"keV"); ThisNuc.SetLevelReference(Key,"AE"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE); ThisNuc.AddLevelGamma(Key,419.925,100.0,61.4131,"M1+E2","keV");                                                                                                                                                                        
    ++Key; ThisNuc.AddEnergyLevel(Key,483.65198,"keV"); ThisNuc.SetLevelReference(Key,"ABDE"); ThisNuc.AddLevelAngMom(Key,2,"+",kFALSE); ThisNuc.SetLevelLifeTime(Key,0.14,"ns"); ThisNuc.AddLevelGamma(Key,86.71388,26.2,396.9373,"M1","keV");
                                                                                               ThisNuc.AddLevelAngMom(Key,3,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,89.951416,9.3,393.6993,"M1+E2","keV");
                                                                                               ThisNuc.AddLevelAngMom(Key,4,"+",kFALSE);                                          ThisNuc.AddLevelGamma(Key,149.97176,42.9,333.6801,"M1","keV");                                                                                                                                                                          
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,160.5603,9.6,323.0922,"??","keV"); 
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,228.153,11.9,255.4986,"??","keV"); 
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,274.0030,100.0,209.6508,"M1+E2","keV"); 
                                                                                                                                                                                  ThisNuc.AddLevelGamma(Key,316.39521,16.0,167.2293,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,586.054,"keV"); ThisNuc.SetLevelReference(Key,"ADFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE); ThisNuc.AddLevelGamma(Key,132.305822,11.9,453.7478,"M1+E2","keV");                                                                                                                                                                         
                                                                                                                                      ThisNuc.AddLevelGamma(Key,252.38111,13.0,333.6801,"??","keV");                                                                                          
                                                                                                                                      ThisNuc.AddLevelGamma(Key,262.933,8.0,323.0922,"??","keV");   
                                                                                                                                      ThisNuc.AddLevelGamma(Key,330.5555,100.0,255.4986,"M1+E2","keV");   
                                                                                                                                      ThisNuc.AddLevelGamma(Key,418.764,37.0,167.2293,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,605.2,"keV"); ThisNuc.SetLevelReference(Key,"FG"); ThisNuc.AddLevelAngMom(Key,-1,"-",kTRUE);                                                                                                                                                                 
    ++Key; ThisNuc.AddEnergyLevel(Key,620.0,"keV"); ThisNuc.SetLevelReference(Key,"I");
    ++Key; ThisNuc.AddEnergyLevel(Key,631.824,"keV"); ThisNuc.SetLevelReference(Key,"ABC"); ThisNuc.AddLevelAngMom(Key,1,"-",kFALSE); ThisNuc.AddLevelGamma(Key,631.834,100.0,0.0,"??","keV");   
                                                                                            ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE);
                                                                                            ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE);
    ++Key; ThisNuc.AddEnergyLevel(Key,642.564922,"keV"); ThisNuc.SetLevelReference(Key,"ABCFG"); ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.AddLevelGamma(Key,217.417121,26.0,425.1484,"??","keV");
                                                                                                 ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE); ThisNuc.AddLevelGamma(Key,331.3087,25.3,311.2612,"??","keV");
                                                                                                                                           ThisNuc.AddLevelGamma(Key,378.1344,100.0,264.4260,"M1+E2","keV");                                       
                                                                                                                                           ThisNuc.AddLevelGamma(Key,449.646,16.0,192.9594,"??","keV");
                                                                                                                                           ThisNuc.AddLevelGamma(Key,564.220,0.0,78.0914,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,658.4435,"keV"); ThisNuc.SetLevelReference(Key,"AB"); ThisNuc.AddLevelGamma(Key,264.7465,13.9,393.6993,"??","keV");
                                                                                            ThisNuc.AddLevelGamma(Key,324.71817,12.5,333.6801,"??","keV");
                                                                                            ThisNuc.AddLevelGamma(Key,491.22422,100.0,167.2293,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,667.55410,"keV"); ThisNuc.SetLevelReference(Key,"A"); ThisNuc.AddLevelGamma(Key,344.462,29.2,323.0922,"??","keV");
                                                                                            ThisNuc.AddLevelGamma(Key,546.016,100.0,121.4967,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,693.9954,"keV"); ThisNuc.SetLevelReference(Key,"AEG"); ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE); ThisNuc.AddLevelGamma(Key,268.8473,9.0,425.1484,"??","keV");
                                                                                             ThisNuc.AddLevelAngMom(Key,5,"-",kFALSE); ThisNuc.AddLevelGamma(Key,280.225,4.8,413.7657,"??","keV");
                                                                                             ThisNuc.AddLevelAngMom(Key,6,"-",kFALSE); ThisNuc.AddLevelGamma(Key,382.686,13.0,311.2612,"??","keV");                                                                                                                                                                          
                                                                                                                                       ThisNuc.AddLevelGamma(Key,422.22210,100.0,271.7630,"??","keV"); 
                                                                                                                                       ThisNuc.AddLevelGamma(Key,501.167,35.0,192.9594,"??","keV");
    ++Key; ThisNuc.AddEnergyLevel(Key,702.72716,"keV"); ThisNuc.SetLevelReference(Key,"AEFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE); ThisNuc.AddLevelGamma(Key,222.28421,7.8,480.436,"??","keV");                                                                                                                                                                         
                                                                                                                                        ThisNuc.AddLevelGamma(Key,288.933,14.3,413.7657,"??","keV");                                                                                          
                                                                                                                                        ThisNuc.AddLevelGamma(Key,437.663,100.0,265.1111,"??","keV");                                                                                                                                                                                                                                                                                      
    ++Key; ThisNuc.AddEnergyLevel(Key,748.2,"keV"); ThisNuc.SetLevelReference(Key,"FG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);                                                                                                                                                                                                                                            
     ++Key; ThisNuc.AddEnergyLevel(Key,790.720,"keV"); ThisNuc.SetLevelReference(Key,"CE");                                                                                
     ++Key; ThisNuc.AddEnergyLevel(Key,796.675,"keV"); ThisNuc.SetLevelReference(Key,"ABC"); ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE); ThisNuc.AddLevelGamma(Key,485.439,63.4,311.2612,"??","keV");
                                                                                             ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.AddLevelGamma(Key,514.128,100.0,282.6499,"??","keV");
                                                                                                                                       ThisNuc.AddLevelGamma(Key,603.606,67.0,192.9594,"??","keV");                                                                                                                                                                          
                                                                                                                                       ThisNuc.AddLevelGamma(Key,719.0420,58.0,78.0914,"??","keV"); 
                                                                                                                                       ThisNuc.AddLevelGamma(Key,796.52,50.0,0.0,"??","keV");                                                                                 
     ++Key; ThisNuc.AddEnergyLevel(Key,810.920,"keV"); ThisNuc.SetLevelReference(Key,"C");                                                                                                                                                                           
     ++Key; ThisNuc.AddEnergyLevel(Key,824.95417,"keV"); ThisNuc.SetLevelReference(Key,"ABC"); ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE); ThisNuc.AddLevelGamma(Key,182.38818,3.5,642.5649,"??","keV");
                                                                                               ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.AddLevelGamma(Key,193.156,9.2,631.824,"??","keV");
                                                                                                                                         ThisNuc.AddLevelGamma(Key,542.298,86.0,282.6499,"??","keV");                                                                                                                                                                          
                                                                                                                                         ThisNuc.AddLevelGamma(Key,747.0012,100.0,78.0914,"??","keV"); 
                                                                                                                                         ThisNuc.AddLevelGamma(Key,824.5419,75.0,0.0,"??","keV");                   
     ++Key; ThisNuc.AddEnergyLevel(Key,855.38,"keV"); ThisNuc.SetLevelReference(Key,"BEG");  
     ++Key; ThisNuc.AddEnergyLevel(Key,868.586,"keV"); ThisNuc.SetLevelReference(Key,"ABEFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE); ThisNuc.AddLevelGamma(Key,471.6710,100.0,396.9373,"??","keV");                                                                                                                                                                 
                                                                                                                                         ThisNuc.AddLevelGamma(Key,474.867,86.0,393.6993,"??","keV");                                                                                      
     ++Key; ThisNuc.AddEnergyLevel(Key,883.3,"keV"); ThisNuc.SetLevelReference(Key,"F");                                                                                                                               
     ++Key; ThisNuc.AddEnergyLevel(Key,920.5711,"keV"); ThisNuc.SetLevelReference(Key,"ABC"); ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE); ThisNuc.AddLevelGamma(Key,841.92,33.0,78.0914,"??","keV");
                                                                                              ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE); ThisNuc.AddLevelGamma(Key,920.7712,100.0,0.0,"??","keV");                                                                                                                            
     ++Key; ThisNuc.AddEnergyLevel(Key,935.57,"keV"); ThisNuc.SetLevelReference(Key,"BCE");
     ++Key; ThisNuc.AddEnergyLevel(Key,948.212,"keV"); ThisNuc.SetLevelReference(Key,"BEF"); ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE);
                                                                                             ThisNuc.AddLevelAngMom(Key,4,"+",kTRUE); 
     ++Key; ThisNuc.AddEnergyLevel(Key,968.716,"keV"); ThisNuc.SetLevelReference(Key,"BCFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,997.910,"keV"); ThisNuc.SetLevelReference(Key,"BEF"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1003.720,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1005.55,"keV"); ThisNuc.SetLevelReference(Key,"BC");
     ++Key; ThisNuc.AddEnergyLevel(Key,1018.55,"keV"); ThisNuc.SetLevelReference(Key,"BC");
     ++Key; ThisNuc.AddEnergyLevel(Key,1030.55,"keV"); ThisNuc.SetLevelReference(Key,"BCFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1043.48,"keV"); ThisNuc.SetLevelReference(Key,"BCEF"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1068.510,"keV"); ThisNuc.SetLevelReference(Key,"BE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1115.48,"keV"); ThisNuc.SetLevelReference(Key,"BEFG");
     ++Key; ThisNuc.AddEnergyLevel(Key,1118.320,"keV"); ThisNuc.SetLevelReference(Key,"CF"); ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE);
                                                                                             ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1121.05,"keV"); ThisNuc.SetLevelReference(Key,"BC");
     ++Key; ThisNuc.AddEnergyLevel(Key,1128.95,"keV"); ThisNuc.SetLevelReference(Key,"BCG");
     ++Key; ThisNuc.AddEnergyLevel(Key,1159.34,"keV"); ThisNuc.SetLevelReference(Key,"BCEF"); ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE);
                                                                                              ThisNuc.AddLevelAngMom(Key,4,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1177.76,"keV"); ThisNuc.SetLevelReference(Key,"BCEFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1186.85,"keV"); ThisNuc.SetLevelReference(Key,"BCG");
     ++Key; ThisNuc.AddEnergyLevel(Key,1189.720,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1199.5,"keV"); ThisNuc.SetLevelReference(Key,"F");
     ++Key; ThisNuc.AddEnergyLevel(Key,1205.65,"keV"); ThisNuc.SetLevelReference(Key,"BCG");
     ++Key; ThisNuc.AddEnergyLevel(Key,1229.65,"keV"); ThisNuc.SetLevelReference(Key,"BCEG");
     ++Key; ThisNuc.AddEnergyLevel(Key,1242.65,"keV"); ThisNuc.SetLevelReference(Key,"BCEFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1247.86,"keV"); ThisNuc.SetLevelReference(Key,"BC"); ThisNuc.AddLevelAngMom(Key,1,"-",kFALSE);
                                                                                            ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE);
                                                                                            ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1258.520,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1273.920,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1301.020,"keV"); ThisNuc.SetLevelReference(Key,"CFG"); ThisNuc.AddLevelAngMom(Key,2,"-",kFALSE);
                                                                                              ThisNuc.AddLevelAngMom(Key,3,"-",kFALSE);
                                                                                              ThisNuc.AddLevelAngMom(Key,4,"-",kFALSE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1335.5,"keV"); ThisNuc.SetLevelReference(Key,"EF"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1382.2,"keV"); ThisNuc.SetLevelReference(Key,"CFG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1416.7,"keV"); ThisNuc.SetLevelReference(Key,"F"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1432.4,"keV"); ThisNuc.SetLevelReference(Key,"FG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1467.30,"keV"); ThisNuc.SetLevelReference(Key,"E");
     ++Key; ThisNuc.AddEnergyLevel(Key,1497.220,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1500.420,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1527.120,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1536.5,"keV"); ThisNuc.SetLevelReference(Key,"FG"); ThisNuc.AddLevelAngMom(Key,-1,"+",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1547.520,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1561.320,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1571.020,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1588.820,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1603.520,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1651.620,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1677.7,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1760.7,"keV"); ThisNuc.SetLevelReference(Key,"CEI");
     ++Key; ThisNuc.AddEnergyLevel(Key,1779.620,"keV"); ThisNuc.SetLevelReference(Key,"CEI");
     ++Key; ThisNuc.AddEnergyLevel(Key,1786.820,"keV"); ThisNuc.SetLevelReference(Key,"CEI");
     ++Key; ThisNuc.AddEnergyLevel(Key,1808.320,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1816.320,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,1835.420,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1879.020,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,1890.50,"keV"); ThisNuc.SetLevelReference(Key,"I"); ThisNuc.AddLevelAngMom(Key,11,"+",kTRUE); 	  	 	 	 	 	 
     ++Key; ThisNuc.AddEnergyLevel(Key,1945.020,"keV"); ThisNuc.SetLevelReference(Key,"CE"); ThisNuc.AddLevelAngMom(Key,-1,"-",kTRUE);
     ++Key; ThisNuc.AddEnergyLevel(Key,1961.120,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2018.020,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2029.520,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2078.920,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2121.320,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2150.720,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2157.120,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2185.420,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2205.020,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2246.020,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2307.30,"keV"); ThisNuc.SetLevelReference(Key,"E");
     ++Key; ThisNuc.AddEnergyLevel(Key,2347.320,"keV"); ThisNuc.SetLevelReference(Key,"CE");
     ++Key; ThisNuc.AddEnergyLevel(Key,2436.620,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2464.120,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2475.320,"keV"); ThisNuc.SetLevelReference(Key,"C");
     ++Key; ThisNuc.AddEnergyLevel(Key,2647.30,"keV"); ThisNuc.SetLevelReference(Key,"E");
     ++Key; ThisNuc.AddEnergyLevel(Key,2807.30,"keV"); ThisNuc.SetLevelReference(Key,"E");
     ++Key; ThisNuc.AddEnergyLevel(Key,3137.30,"keV"); ThisNuc.SetLevelReference(Key,"E");
     ++Key; ThisNuc.AddEnergyLevel(Key,3800.0,"keV"); ThisNuc.SetLevelReference(Key,"I");
     ++Key; ThisNuc.AddEnergyLevel(Key,6100.0,"keV"); ThisNuc.SetLevelReference(Key,"I");
     ++Key; ThisNuc.AddEnergyLevel(Key,6806.3815,"keV"); ThisNuc.AddLevelAngMom(Key,2,"+",kTRUE);
                                                         ThisNuc.AddLevelAngMom(Key,3,"+",kTRUE);                                             
                                                                            
    // Return the final answer:
    return ThisNuc;
}
