name: pre build
description: 'steps before building R3BRoot'

runs:
  using: composite
  steps:
    - name: set env variables
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        echo "UCESB_DIR=$GITHUB_WORKSPACE/ucesb/" >> $GITHUB_ENV
        echo "ATIMAPATH=$GITHUB_WORKSPACE/catima/" >> $GITHUB_ENV
        if [ "${{ matrix.cpp }}" == "20" ]; then
          export SIMPATH=${CVMDIR}/${{ matrix.os }}/fairsoft/cpp20/${{ matrix.fsv }}
          echo "SIMPATH=${SIMPATH}" >> $GITHUB_ENV
          echo "FAIRROOTPATH=${CVMDIR}/${{ matrix.os }}/fairroot/cpp20/v18.8.2_${{ matrix.fsv }}" >> $GITHUB_ENV
          echo "${SIMPATH}/bin" >> $GITHUB_PATH
        else
          if [ "${{ matrix.os }}" == "debian13" ]; then
            export SIMPATH=${CVMDIR}/${{ matrix.os }}/fairsoft/cpp17/${{ matrix.fsv }}
            echo "SIMPATH=${SIMPATH}" >> $GITHUB_ENV
            echo "FAIRROOTPATH=${CVMDIR}/${{ matrix.os }}/fairroot/cpp17/v18.8.2_${{ matrix.fsv }}" >> $GITHUB_ENV
            echo "${SIMPATH}/bin" >> $GITHUB_PATH
          else
            export SIMPATH=${CVMDIR}/${{ matrix.os }}/fairsoft/${{ matrix.fsv }}
            echo "SIMPATH=${SIMPATH}" >> $GITHUB_ENV
            echo "FAIRROOTPATH=${CVMDIR}/${{ matrix.os }}/fairroot/v18.8.2_${{ matrix.fsv }}" >> $GITHUB_ENV
            echo "${SIMPATH}/bin" >> $GITHUB_PATH
          fi
        fi
        # variables for ccache
        echo "CCACHE_BASEDIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
        echo "CCACHE_DIR=${GITHUB_WORKSPACE}/.ccache" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
        echo "SOURCEDIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "BUILDDIR=$GITHUB_WORKSPACE/build" >> $GITHUB_ENV
        echo "cacheSHA=$([[ ${{github.event_name}} = "push" ]] && git rev-parse --short HEAD || git rev-parse --short HEAD^)" >> $GITHUB_ENV
      shell: bash

    - name: mount cvmfs
      run: |
        apt-get update
        apt-get install --fix-missing -y sudo wget gnupg lsb-release
        sudo -H pip3 install --ignore-installed -U conan
        wget https://cernbox.cern.ch/remote.php/dav/public-files/RmnTeeOZpYjCJQb/masterkey.gsi.de.pub
        mkdir -p /etc/cvmfs/keys
        mv masterkey.gsi.de.pub /etc/cvmfs/keys
        cp .github/config/fairsoft.gsi.de.conf /etc/cvmfs/config.d
        echo "CVMFS_USER=$(whoami)" >> /etc/cvmfs/config.d/fairsoft.gsi.de.conf
        mkdir -p ${CVMDIR}
        mount -t cvmfs fairsoft.gsi.de ${CVMDIR}
        mkdir -p ${UCESB_DIR}
        mkdir -p ${ATIMAPATH}
        mkdir -p ${CCACHE_DIR}
      shell: bash
