/* Generated by Together */
#include <iostream>
#include <stdlib.h>

#include "FairGeoLoader.h"
#include "FairGeoInterface.h"
#include "FairGeoRootBuilder.h"
#include "FairRuntimeDb.h"
#include "TObjArray.h"
#include "FairRun.h"
#include "FairGeoVolume.h"
#include "FairGeoNode.h"

#include "R3BTarget.h"
#include "R3BGeoPassivePar.h"
#include "R3BGeoTarget.h"

using namespace std;


R3BTarget::~R3BTarget()
{
  if(fTargetName) {
    delete fTargetName;
  }
}


R3BTarget::R3BTarget()
{
  fTargetName = NULL;
}


R3BTarget::R3BTarget(const char * name,  const char * title)
  : R3BModule(name ,title)
{
  fTargetName = new TString(name);
}


void R3BTarget::ConstructGeometry()
{
  TString fileName = GetGeometryFileName();
  if(fileName.EndsWith(".root")) {
    LOG(INFO) << "Constructing Target geometry from ROOT file " << fileName.Data() << FairLogger::endl;
    ConstructRootGeometry();
  } else {
    LOG(FATAL) << "Target geometry file name is not set" << FairLogger::endl;
    exit(1);
  }
}


Bool_t R3BTarget::CheckIfSensitive(std::string name)
{
  return kFALSE;
}


ClassImp(R3BTarget)
