#!/bin/bash


root -l << EOF
.L r3blandsim.C
r3blandsim(255)
.q
EOF


root -l << EOF
.L r3blandsim.C
r3blandsim(498)
.q
EOF


root -l << EOF
.L r3blandsim.C
r3blandsim(799)
.q
EOF


root -l << EOF
.L r3blandsim.C
r3blandsim(1014)
.q
EOF


root -l << EOF
.L r3blandsim.C
r3blandsim(1500)
.q
EOF


