#!/bin/bash


root -l << EOF
.L preCalibr.C
preCalibr(255)
.q
EOF


root -l << EOF
.L preCalibr.C
preCalibr(498)
.q
EOF


root -l << EOF
.L preCalibr.C
preCalibr(799)
.q
EOF


root -l << EOF
.L preCalibr.C
preCalibr(1014)
.q
EOF


root -l << EOF
.L preCalibr.C
preCalibr(1500)
.q
EOF


