name: static analysis
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

permissions: write-all

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: 
      image: yanzhaowang/cvmfs_clang:v15
      volumes:
        - /tmp:/cvmfs
      env:
        CVMDIR: /cvmfs/fairsoft.gsi.de
      options: --user root --privileged  --ulimit nofile=10000:10000 --cap-add SYS_ADMIN --device /dev/fuse
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: mount cvmfs
      run: |
        wget https://cernbox.cern.ch/remote.php/dav/public-files/RmnTeeOZpYjCJQb/masterkey.gsi.de.pub
        mv masterkey.gsi.de.pub /etc/cvmfs/keys
        cp .githubfiles/fairsoft.gsi.de.conf /etc/cvmfs/config.d
        mkdir -p ${CVMDIR}
        mount -t cvmfs fairsoft.gsi.de ${CVMDIR}

    - name: cmake configure
      run: |
        export SIMPATH=${CVMDIR}/debian10/fairsoft/nov22p1
        export FAIRROOTPATH=${CVMDIR}/debian10/fairroot/v18.8.0_fs_nov22p1
        export PATH=${SIMPATH}/bin:$PATH
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git clone https://github.com/R3BRootGroup/macros.git
        cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DBUILD_GEOMETRY=OFF -DUSE_DIFFERENT_COMPILER=TRUE

    - name: clang-tidy check
      run: |
        mkdir -p clang-tidy-result
        git diff -U0 HEAD^ | clang-tidy-diff-15.py -p1 -path build \
        -iregex '.*\.(cpp|cc|c\+\+|cxx|cl|h|hh|hpp|m|mm|inc)' \
        -export-fixes clang-tidy-result/fixes.yml |\
        sed 's/\(^.*\):\([0-9]*\):\([0-9]*\): warning:/::warning file=\1,line=\2,col=\3::/'
        echo "WARN_NUM=$(grep -w "^ *Message:" clang-tidy-result/fixes.yml | wc -l | xargs)" >> $GITHUB_ENV

    - name: clang-tidy results
      run: |
          if [ "${{ env.WARN_NUM }}" -eq "0" ]; then
            echo "::notice::All clean, LGTM!"
          else
            cat clang-tidy-result/fixes.yml
            echo "::notice::Clang-tidy generates ${{ env.WARN_NUM }} warnings! Please fix them before being merged."
            exit 1
          fi
      shell: bash

