name: Cleanup Caches on PR Close

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - 202402_fast

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R R3BRootGroup/R3BRoot -B ${{ github.event.pull_request.base.ref }} -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R R3BRootGroup/R3BRoot -B ${{ github.event.pull_request.base.ref }} --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

