#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Cleanup old caches

on:
  schedule:
    - cron: '0 0 1 */2 *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug gh CLI
        run: |
          gh --version
          gh auth status
          gh extension list

      - name: Update GitHub CLI
        run: sudo apt-get install gh

      - name: Install and Verify gh-actions-cache Extension
        run: |
          gh extension install actions/gh-actions-cache || exit 1
          gh extension list | grep gh-actions-cache || (echo "Extension installation failed" && exit 1)

      - name: Test actions-cache list
        run: |
          gh actions-cache list -R R3BRootGroup/R3BRoot -L 5 || echo "Failed to list caches"

      - name: Cleanup
        run: |
          echo "Fetching list of cache keys"
          cacheKeys=$(gh actions-cache list -R R3BRootGroup/R3BRoot -L 100 | cut -f 1 | grep -v 'build-deps') || exit 1

          set +e
          echo "Deleting old caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R R3BRootGroup/R3BRoot --confirm || echo "Failed to delete $cacheKey"
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

