# Requires following secrets and variables:
#
# variables:
# - DOCKER_REPO: repository to be pushed to.
# - DOCKER_USERNAME: the user name of the repository owner.
# - SYLABS_USERNAME: the user name of sylab repo owner
#
# secrets:
# - DOCKER_TOKEN: access token to dockerhub
# - SYLABS_TOKEN: access token to sylab server

name: deploy-container

on:
  push:
    branches: [ edwin_dev ]
  workflow_dispatch:


jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: util/container
          tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO }}
          build-args: |
            THREAD_NUM=4 
            R3B_BRNAME=${{ github.head_ref || github.ref_name }}


  apptainer-build:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: build apptainer and push
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer
          apptainer remote add --no-login SylabsCloud cloud.sycloud.io
          echo "${{ secrets.SYLABS_TOKEN }}" | apptainer remote login SylabsCloud
          set -e
          apptainer delete -F library://${{ vars.SYLABS_USERNAME }}/r3bdev/${image_tag} || true
          sudo apptainer build --notest neuland.sif ./util/container/neuland.def
          apptainer push -D "For testing" -U neuland.sif library://${{ vars.SYLABS_USERNAME }}/r3bdev/${image_tag}
        shell: bash
        env:
          image_tag: 'neuland:latest'
