name: CI C11++

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run Dart.sh
        run: |
          cd $GITHUB_WORKSPACE
          git clone -b dev https://github.com/R3BRootGroup/macros.git
          singularity exec /data.local2/kresan/debian10-jun19p2-v18.2.1-ucesb.sif $PWD/.githubfiles/run_build_test_jun19p2.sh
