name: publish-doc
on:
  push:
    branches:
      - neuland_new_calibration
  workflow_dispatch:

jobs:
  artifact-gen:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: run doxygen
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen graphviz ninja-build libjs-mathjax cmake
          cmake --workflow --preset doxygen

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/doc/html
          retention-days: 1

  publish-doxygen:
    runs-on: ubuntu-latest
    needs: artifact-gen
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
