# #
# # SPDX-License-Identifier: LGPL-3.0-or-later

# name: static analysis
# on:
#   push:
#     branches: [dev, edwin_dev]
#   pull_request:
#     branches: [dev, edwin_dev]

#   workflow_dispatch:

# permissions:
#   pull-requests: write
#   contents: write

# jobs:
#   clang-lint:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#     strategy:
#       matrix:
#         preset: [default]
#         os: [ubuntu-latest]
#     container:
#       image: yanzhaowang/fairroot:${{ matrix.os }}
#       options: --user root --privileged
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           submodules: 'true'

#       - name: install sudo
#         run: |
#           apt-get install -y sudo
#           sudo -H python3 -m pip install conan

#       - name: configure r3broot
#         uses: './.github/actions/r3bbuild-steps'
#         with:
#           build-needed: 'false'

#       - name: Run clang-format style check for C/C++/Protobuf programs.
#         uses: cpp-linter/cpp-linter-action@v2
#         id: linter
#         env:
#           GITHUB_TOKEN: ${{ secrets.CPPLINTER_TOKEN }}
#         with:
#           style: 'file'
#           tidy-checks: ''
#           version: 18
#           lines-changed-only: true
#           database: '${{ github.workspace }}/build'
#           thread-comments: update
#           tidy-review: true
#           file-annotations: true
#           format-review: true
#           passive-reviews: true
#           extensions: 'h,cxx'
#           ignore: '*|!neuland|!r3bbase|!r3bdata|!r3bsource|ext_h101*'

#       - name: Fail fast?!
#         if: steps.linter.outputs.checks-failed > 0
#         run: exit 1
